# Generated by Django 4.1.3 on 2022-12-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeurl',
            name='longurl',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='storeurl',
            name='shorturl',
            field=models.URLField(unique=True),
        ),
    ]
