# Generated by Django 4.1.3 on 2022-12-28 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_storeurl_longurl"),
    ]

    operations = [
        migrations.RemoveField(model_name="storeurl", name="longurl",),
    ]
