# Generated by Django 4.1.3 on 2022-12-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_storeurl_longurl_alter_storeurl_shorturl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storeurl",
            name="shorturl",
            field=models.CharField(max_length=120),
        ),
    ]
