# Generated by Django 4.1.3 on 2022-12-30 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_storeurl_longurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeurl',
            name='created_date',
            field=models.DateField(default=datetime.date(2022, 12, 30)),
        ),
    ]
