# Generated by Django 4.1.3 on 2022-12-30 08:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_storeurl_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeurl',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
