# Generated by Django 4.1.3 on 2022-12-30 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_storeurl_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeurl',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 30, 8, 54, 58, 361296)),
        ),
    ]
