# Generated by Django 4.1.3 on 2022-12-30 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_storeurl_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeurl',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 30, 9, 26, 34, 343402)),
        ),
    ]
